<a href="https://colab.research.google.com/github/windnaslinux/pytorch/blob/dev/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello pytorch")

Hello pytorch


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


**Introduction to Tensors**

Creating tensors

Pytorch tensors are creating using torch.tensors = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Get tensor back as python int
scalar.item()

7

In [4]:
# Vector
vector = torch.tensor([7, 8])
vector

tensor([7, 8])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

# Use torch.arange

In [7]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Create tensors like

In [8]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes
### Tensors datatype is one of the 3 big errors with pytorch & deep learning
 1. Tensors not right datatype
 2. Tensors not right shape
 3. Tensors not on the right device

In [9]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [10]:
float_32_tensor.dtype

torch.float32

In [11]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [12]:
result = float_16_tensor * float_32_tensor
result.dtype

torch.float32

### Get information from tensor (tensor attributes)
 1. Tensors not right datatype - to get datatype from a tensor, use: tensor.dtype
 2. Tensors not right shape- to get shape from a tensor, use: tensor.shape
 3. Tensors not on the right device- to get device from a tensor, use: tensor.device

In [13]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8728, 0.8317, 0.5383, 0.9773],
        [0.5938, 0.3105, 0.2273, 0.1873],
        [0.7735, 0.1868, 0.9320, 0.1412]])

In [14]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8728, 0.8317, 0.5383, 0.9773],
        [0.5938, 0.3105, 0.2273, 0.1873],
        [0.7735, 0.1868, 0.9320, 0.1412]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Maniputlating Tensors (tensors operations)

Tensor operations include:
 * Addition
 * Subtraction
 * Multiplication (element-wise)
 * Division
 * Matrix multiplication

In [15]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [16]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [17]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [18]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [19]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix multiplication
### Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. matrix mutliplication (dot product)

In [20]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [23]:
# Matrix multiplication
print(tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3])


tensor(14)

In [24]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.91 ms, sys: 0 ns, total: 2.91 ms
Wall time: 2.72 ms


In [25]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 451 µs, sys: 0 ns, total: 451 µs
Wall time: 301 µs


tensor(14)